# Generated by Django 3.2.7 on 2021-10-01 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='file',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='content',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='work',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
