# Generated by Django 3.2.7 on 2021-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_auto_20211001_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='estimate_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
