# Generated by Django 3.2.7 on 2021-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_work_estimate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
