# Generated by Django 3.2.7 on 2021-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Incomplete', 'Incomplete'), ('In Process', 'In Process'), ('Complete', 'Complete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='subject',
            field=models.CharField(blank=True, choices=[('Finance', 'Finance'), ('Admin', 'Admin'), ('Development', 'Development'), ('Testing', 'Testing'), ('Audit', 'Audit'), ('IT', 'IT')], max_length=100),
        ),
    ]
