# Generated by Django 3.2.7 on 2021-10-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_alter_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
